### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by luan0ap** [TheSlipper/Just-Monika#1]
I need help for compile the game. I'm not programmer in C++

**Comment by TheSlipper** [comment]
Hi luan0ap. I'm sorry but I will have to disappoint you - I have dropped the project some time ago after I lost my _almost_ finished game without having it uploaded earlier to github. After that I dropped this project. 

 I have never thought that the DDLC game would get so popular and therefore I have not edited the README.md to let the people know that this project is not active anymore. Now I know I should've done that.


  The only thing that you can find in this repo is a program that displays DDLC-ish like menu.

However if you're still willing to compile the game you should check out the SFML's tutorials for the 2.4 version (https://www.sfml-dev.org/tutorials/2.4/).
